name: 'Validations'
description: 'Lint and Security Checks'
runs:
  using: "composite"
  steps:
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
      shell: bash
    - name: Install gosec
      run: go install github.com/securego/gosec/v2/cmd/gosec@v2.8.1
      shell: bash
    - name: Run lint
      run: golangci-lint run
      shell: bash
    - name: Run gosec
      run: gosec ./...
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
